# Generated by Django 5.2 on 2025-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('florist', 'Florist'), ('courier', 'Courier'), ('client', 'Client')], default='client', max_length=20, verbose_name='Role'),
        ),
    ]
